#!/bin/bash

#PBS -N GEMMA_CR_Binary
#PBS -S /bin/bash
#PBS -l walltime=8:00:00
#PBS -l nodes=1:ppn=4
#PBS -j oe
#PBS -o /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/logs/${PBS_JOBID}_GEMMA_GWAS_noIBD_newcovs_CharlesRiver_binary.out
#PBS -q condo

#################################################################################
#			REPORTING DATA FOR OUTPUT SUMMARY			#
#################################################################################
echo -n 'Started job at : ' ; date
echo " "
echo "-------------------"
echo "This is a $PBS_ENVIRONMENT job"
echo "This job was submitted to the queue: $PBS_QUEUE"
echo "The job's id is: $PBS_JOBID"
echo "-------------------"
echo "The master node of this job is: $PBS_O_HOST"

# --- the nodes allocated to this job are listed in the
#     file PBS_NODEFILE

# --- count the number of processors allocated to this run 
# --- $NPROCS is required by mpirun.
NPROCS=`wc -l < $PBS_NODEFILE`
NNODES=`uniq $PBS_NODEFILE | wc -l`
echo "This job is using $NPROCS CPU(s) on the following $NNODES node(s):"
echo "-----------------------"
uniq $PBS_NODEFILE | sort
echo "-----------------------"
################################################################################

#################################################################
# 			Job Execution 			#
#################################################################

#####ESTIMATE RELATEDNESS MATRIX FROM GENOTYPES#####
chrom=`head -$PBS_ARRAYID /oasis/tscc/scratch/agileta/SD/GBS/chroms_rat.list | tail -1`

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.pheno -gk 1 -o allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -gk 1 -o allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly

##################################################################################################################################################
### Harlan/CharlesRiver Only - Primary Phenotypes   ######
##########################################################

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 1 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.LevPressDay1_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 2 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.MagEntryDay1_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 3 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.MagEntryNCSDay1_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 4 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.ProbLevDay1_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 5 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.ProbMagDay1_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 6 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.AvgLatLevDay1_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 7 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.AvgLatMagDay1_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 8 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.ResponseBiasDay1_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 9 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.ProbDiffDay1_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 10 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.LatencyScoreDay1_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 11 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.IndexScoreDay1_normalized

##################################################################################################################################################
### Harlan/CharlesRiver Only - Weight GWAS   ######
##########################################################

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.weights.pheno -n 1 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.weights.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.BodyWeight

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.weights.pheno -n 1 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.weights.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.BodyWeight


##################################################################################################################################################### Harlan/CharlesRiver - PC1 for Each Phenotype Across the 5 Days  ######
###########################################################################

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 82 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.PhenoPC1_LevPress_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 83 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.PhenoPC1_MagEntry_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 84 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.PhenoPC1_MagEntryNCS_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 85 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.PhenoPC1_ProbLev_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 86 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.PhenoPC1_ProbMag_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 87 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.PhenoPC1_AvgLatLev_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 88 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.PhenoPC1_AvgLatMag_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 89 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.PhenoPC1_ResponseBias_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 90 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.PhenoPC1_ProbDiff_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 91 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.PhenoPC1_LatencyScore_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.4GEMMA.pheno -n 92 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.HarlanOnly.dosages.gwas.PhenoPC1_IndexScore_normalized_regressed

##################################################################################################################################################### Harlan/CharlesRiver - PC1 for Each Day Across all Phenotypes    ######
###########################################################################

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.pheno -n 67 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.PhenoPC1_Day1_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.pheno -n 70 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.PhenoPC1_Day2_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.pheno -n 73 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.PhenoPC1_Day3_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.pheno -n 76 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.PhenoPC1_Day4_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.pheno -n 79 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.PhenoPC1_Day5_normalized_regressed

##################################################################################################################################################### Harlan/CharlesRiver - PC1/2/3 for All Phenos on All Days        ######
###########################################################################

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.pheno -n 93 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.PhenoPC1_AllPhenosAllDays_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.pheno -n 94 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.PhenoPC2_AllPhenosAllDays_normalized_regressed

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.pheno -n 95 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.PhenoPC3_AllPhenosAllDays_normalized_regressed


#################################################################################################################################################
### All Samples - Binary Coding of Phenotypes - Harlan/CharlesRiver   ######
############################################################################

/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.binary.pheno -n 1 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.IndexScore0D4D5_binary

/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.binary.pheno -n 2 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.IndexScore25D4D5_binary

/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.binary.pheno -n 3 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.IndexScore50D4D5_binary

/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.binary.pheno -n 4 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.LevPressD4D5_binary

/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.binary.pheno -n 5 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.MagEntryD4D5_binary

/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.binary.pheno -n 6 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.ProbLevD4D5_binary

/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.binary.pheno -n 7 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.ProbMagD4D5_binary

/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.binary.pheno -n 8 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.AvgLatLevD4D5_binary

/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.binary.pheno -n 9 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.4GEMMA.covs -lmm 4 -o ${chrom}.allSamps.90DR2.maf01.hweE7.noIBD.CharlesRiverOnly.dosages.gwas.AvgLatMagD4D5_binary

##################################################################################################################################################
### Harlan/Harlan - Simulated Phenotypes   ######
##############################################################

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.Harlan.90DR2.hweE7.maf01.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/SD_phenotypes_D4D5averages_simulated_Harlan_4GEMMA.txt -n 1 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.Harlan.90DR2.hweE7.maf01.dosages.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.Harlan.90DR2.hweE7.maf01.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps_Harlan.covs -lmm 4 -o ${chrom}.allSamps.Harlan.90DR2.hwe7.maf01.dosages.gwas.simNormal

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.Harlan.90DR2.hweE7.maf01.dosages -p /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/SD_phenotypes_D4D5averages_simulated_Harlan_4GEMMA.txt -n 2 -k /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/LOCO/GRMs/allExcept${chrom}.allSamps.Harlan.90DR2.hweE7.maf01.dosages.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/variants/dosageFiles/${chrom}.allSamps.Harlan.90DR2.hweE7.maf01.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/variants/GEMMA_files/allChr.allSamps_Harlan.covs -lmm 4 -o ${chrom}.allSamps.Harlan.90DR2.hwe7.maf01.dosages.gwas.simNormal_Truncated

##################################################################################################################################################
### Harlan/Harlan Only - STITCH DOSAGE DATA   ######
##########################################################

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage -p /oasis/tscc/scratch/agileta/SD/GBS/STITCH/SD_phenotypes_D4D5averages_normalized_Harlan_4GEMMA_ANGSDcopy.txt -n 1 -k /oasis/tscc/scratch/agileta/SD/GBS/STITCH/GRMs/stitch.allExcept${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/STITCH/stitch.Harlan.ANGSDorder.covs -lmm 4 -o stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage.gwas.IndexD4D5_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage -p /oasis/tscc/scratch/agileta/SD/GBS/STITCH/SD_phenotypes_D4D5averages_normalized_Harlan_4GEMMA_ANGSDcopy.txt -n 2 -k /oasis/tscc/scratch/agileta/SD/GBS/STITCH/GRMs/stitch.allExcept${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/STITCH/stitch.Harlan.ANGSDorder.covs -lmm 4 -o stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage.gwas.LevPressD4D5_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage -p /oasis/tscc/scratch/agileta/SD/GBS/STITCH/SD_phenotypes_D4D5averages_normalized_Harlan_4GEMMA_ANGSDcopy.txt -n 3 -k /oasis/tscc/scratch/agileta/SD/GBS/STITCH/GRMs/stitch.allExcept${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/STITCH/stitch.Harlan.ANGSDorder.covs -lmm 4 -o stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage.gwas.MagEntryD4D5_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage -p /oasis/tscc/scratch/agileta/SD/GBS/STITCH/SD_phenotypes_D4D5averages_normalized_Harlan_4GEMMA_ANGSDcopy.txt -n 4 -k /oasis/tscc/scratch/agileta/SD/GBS/STITCH/GRMs/stitch.allExcept${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/STITCH/stitch.Harlan.ANGSDorder.covs -lmm 4 -o stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage.gwas.MagEntryNCSD4D5_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage -p /oasis/tscc/scratch/agileta/SD/GBS/STITCH/SD_phenotypes_D4D5averages_normalized_Harlan_4GEMMA_ANGSDcopy.txt -n 5 -k /oasis/tscc/scratch/agileta/SD/GBS/STITCH/GRMs/stitch.allExcept${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/STITCH/stitch.Harlan.ANGSDorder.covs -lmm 4 -o stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage.gwas.ProbLevD4D5_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage -p /oasis/tscc/scratch/agileta/SD/GBS/STITCH/SD_phenotypes_D4D5averages_normalized_Harlan_4GEMMA_ANGSDcopy.txt -n 6 -k /oasis/tscc/scratch/agileta/SD/GBS/STITCH/GRMs/stitch.allExcept${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/STITCH/stitch.Harlan.ANGSDorder.covs -lmm 4 -o stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage.gwas.ProbMagD4D5_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage -p /oasis/tscc/scratch/agileta/SD/GBS/STITCH/SD_phenotypes_D4D5averages_normalized_Harlan_4GEMMA_ANGSDcopy.txt -n 7 -k /oasis/tscc/scratch/agileta/SD/GBS/STITCH/GRMs/stitch.allExcept${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/STITCH/stitch.Harlan.ANGSDorder.covs -lmm 4 -o stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage.gwas.AvgLatLevD4D5_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage -p /oasis/tscc/scratch/agileta/SD/GBS/STITCH/SD_phenotypes_D4D5averages_normalized_Harlan_4GEMMA_ANGSDcopy.txt -n 8 -k /oasis/tscc/scratch/agileta/SD/GBS/STITCH/GRMs/stitch.allExcept${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/STITCH/stitch.Harlan.ANGSDorder.covs -lmm 4 -o stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage.gwas.AvgLatMagD4D5_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage -p /oasis/tscc/scratch/agileta/SD/GBS/STITCH/SD_phenotypes_D4D5averages_normalized_Harlan_4GEMMA_ANGSDcopy.txt -n 9 -k /oasis/tscc/scratch/agileta/SD/GBS/STITCH/GRMs/stitch.allExcept${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/STITCH/stitch.Harlan.ANGSDorder.covs -lmm 4 -o stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage.gwas.ResponseBiasD4D5_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage -p /oasis/tscc/scratch/agileta/SD/GBS/STITCH/SD_phenotypes_D4D5averages_normalized_Harlan_4GEMMA_ANGSDcopy.txt -n 10 -k /oasis/tscc/scratch/agileta/SD/GBS/STITCH/GRMs/stitch.allExcept${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/STITCH/stitch.Harlan.ANGSDorder.covs -lmm 4 -o stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage.gwas.ProbDiffD4D5_normalized

#/projects/ps-palmer/software/local/src/gemma -g /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage -p /oasis/tscc/scratch/agileta/SD/GBS/STITCH/SD_phenotypes_D4D5averages_normalized_Harlan_4GEMMA_ANGSDcopy.txt -n 11 -k /oasis/tscc/scratch/agileta/SD/GBS/STITCH/GRMs/stitch.allExcept${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.cXX.txt -a /oasis/tscc/scratch/agileta/SD/GBS/STITCH/dosages/stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.snpinfo -c /oasis/tscc/scratch/agileta/SD/GBS/STITCH/stitch.Harlan.ANGSDorder.covs -lmm 4 -o stitch.${chrom}.Harlan.INFO90.hweE7.maf01.ANGSDorder.dosage.gwas.LatencyScoreD4D5_normalized


###############################################################
echo -n 'Ended job at  : ' ; date